name = "Alice"
license = "DBADPL"
licenselink = "https://github.com/lixk28/Alice/blob/main/LICENSE"
description = "MistY's OWN Hugo Theme"
homepage = "https://github.com/lixk28/Alice"
min_version = "0.20"

authors = [
  { name = "Xuekun Li", homepage = "https://github.com/lixk28" },
  { name = "Akbar Hamaminatu", homepage = "https://ngoding.id" }
]
