languageCode = "en-US"
hasCJKLanguage = true
title = "Hugo Alice"
theme = "Alice"
themesDir = "../.."

# Alice parameters
[params]
    title = "Hugo Alice"
    author = "Xuekun Li"
    description = ""
    mainSections = ["posts"]
    keywords = []
    dateFmt = "2006-01-02"
    license = "DBADPL"

    [params.header]
        blogo = "images/HugoAliceLogo.webp"
        title = "Hugo Alice"
        tagline = "so damn classic"

    [params.footer]
        # Should display site generator (Hugo) and theme (Alice) 🥰
        showHugoAlice = true
        # Copy{left,right} statement, HTML is allowed
        copymid = ""
        # License statement, HTML is allowed
        license = 'Licensed under the <a href="https://dbad-license.org/"><b>DBADPL</b></a>'
        # Creation year of your site
        since = 2024
        # Creator name, HTML is allowed
        creator = "<b>MistY</b>"

    [params.home]
        [params.home.pagination]
            # Only posts in given sections will be paginated
            sections = ["posts"]
            # The number of posts per page
            pagerSize = 3
            # Previous indicator, HTML is allowed
            prev = "&laquo;"
            # Next indicator, HTML is allowed
            next = "&raquo;"
            # First indicator, HTML is allowed
            first = "&laquo;&laquo;"
            # Last indicator, HTML is allowed
            last = "&raquo;&raquo;"

        [params.home.sidebar]
            [[params.home.sidebar.items]]
                id = "news"
                title = "News"
                weight = 1
                enable = true
                [params.home.sidebar.items.args]
                    size = 5
                    dateFmt = "2006-01-02"
                    # Delimiter between date and news, HTML is allowed
                    delimiter = "&ensp;"

            [[params.home.sidebar.items]]
                # Will be your side item template name and html element id
                id = "recent-updates"
                title = "Recent Updates"
                weight = 2
                enable = true
                [params.home.sidebar.items.args]
                    size = 5
                    dateFmt = "2006-01-02"
                    # Delimiter between date and post title, HTML is allowed
                    delimiter = "&ensp;"

            [[params.home.sidebar.items]]
                id = "tag-list"
                title = "Tags"
                weight = 3
                enable = true
                [params.home.sidebar.items.args]
                    size = 10
                    delimiter = "&emsp;"
                    # Sort by {count | random}, default is count
                    sortBy = "count"

            [[params.home.sidebar.items]]
                id = "category-list"
                title = "Categories"
                weight = 4
                enable = true
                [params.home.sidebar.items.args]
                    size = 5
                    delimiter = "&emsp;"
                    # Sort by {count | random}, default is count
                    sortBy = "count"

    [params.codeblock]
        maxLinesOfCode = 64

    [params.tex]
        # mathjax or katex
        engine = 'mathjax'
        inlineBeginDelimiter = ''
        inlineEndDelimiter = ''
        blockBeginDelimiter = ''
        blockEndDelimiter = ''

    [params.imgproc]
        enable = false
        # Default format for processed images
        format = "webp"
        # 0-100, image quality for compressed formats
        quality = 75
        # Image sizes for responsive images
        sizes = ["420", "789", "1019", "1430", "2048"]
        # Image resampling filter (Box, Lanczos, CatmullRom, MitchellNetravali, Linear, and NearestNeighbor)
        resamplingFilter = "Lanczos"
        # Default format for fallback images
        fallbackFormat = "jpg"
        # Default fallback image size
        fallbackSize = "789"

    [params.lightbox]
        # fancybox or glightbox
        vendor = 'fancybox'

    # waline v3 comment system
    [params.waline]
        enable = false
        # required
        serverURL = 'your-waline-server-domain.example.com'
        # optional
        # default language, https://waline.js.org/guide/features/i18n.html
        language = 'en'
        reaction = false

    # code editor
    [params.codeeditor]
        # ('codemirror5' | 'cm5') or ('codemirror6' | 'cm6')
        # codemirror5 is recommended
        # codemirror6 is still under development, it lacks a lot of common language support,
        # and you have to bundle the script yourself
        vendor = 'codemirror5'
        # https://codemirror.net/5/doc/manual.html#addons
        addons = []


# Hugo parameters with Alice default initialization
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe = true
    [markup.goldmark.parser]
        wrapStandAloneImageWithinParagraph = false
        [markup.goldmark.parser.attribute]
            block = true
            title = true
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = true
        hl_Lines = ''
        hl_inline = false
        lineAnchors = ''
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = false
        noHl = false
        tabWidth = 4
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 4
        ordered = false
    [markup.goldmark]
        [markup.goldmark.extensions.typographer]
            emDash = '&HorizontalLine;&HorizontalLine;'
            leftDoubleQuote = '"'
            rightDoubleQuote = '"'
            leftSingleQuote = "'"
            rightSingleQuote = "'"

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 2

    [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 3

    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 4

    [[menu.main]]
        identifier = "friends"
        name = "Friends"
        url = "/friends/"
        weight = 5

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 6

    [[menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/index.xml"
        weight = 7
[sitemap]
    changefreq = 'weekly'
    filename = 'sitemap.xml'
    priority = 0.5
